application: t-roomz
version: 0
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /
  static_files: index.html
  upload: index.html
- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
- url: /.*
  static_files: 404.html
  upload: 404.html


